// Code generated by protoc-gen-go. DO NOT EDIT.
// source: version.proto

/*
Package version is a generated protocol buffer package.

It is generated from these files:
	version.proto

It has these top-level messages:
	VersionMessage
*/
package version

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VersionMessage struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Build   string `protobuf:"bytes,2,opt,name=build" json:"build,omitempty"`
}

func (m *VersionMessage) Reset()                    { *m = VersionMessage{} }
func (m *VersionMessage) String() string            { return proto.CompactTextString(m) }
func (*VersionMessage) ProtoMessage()               {}
func (*VersionMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VersionMessage) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *VersionMessage) GetBuild() string {
	if m != nil {
		return m.Build
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionMessage)(nil), "version.VersionMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Version service

type VersionClient interface {
	Version(ctx context.Context, in *VersionMessage, opts ...grpc.CallOption) (*VersionMessage, error)
}

type versionClient struct {
	cc *grpc.ClientConn
}

func NewVersionClient(cc *grpc.ClientConn) VersionClient {
	return &versionClient{cc}
}

func (c *versionClient) Version(ctx context.Context, in *VersionMessage, opts ...grpc.CallOption) (*VersionMessage, error) {
	out := new(VersionMessage)
	err := grpc.Invoke(ctx, "/version.Version/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Version service

type VersionServer interface {
	Version(context.Context, *VersionMessage) (*VersionMessage, error)
}

func RegisterVersionServer(s *grpc.Server, srv VersionServer) {
	s.RegisterService(&_Version_serviceDesc, srv)
}

func _Version_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/version.Version/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServer).Version(ctx, req.(*VersionMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Version_serviceDesc = grpc.ServiceDesc{
	ServiceName: "version.Version",
	HandlerType: (*VersionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Version_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "version.proto",
}

func init() { proto.RegisterFile("version.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4b, 0x2d, 0x2a,
	0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x1c, 0xb8,
	0xf8, 0xc2, 0x20, 0x4c, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x21, 0x09, 0x2e, 0x98, 0xa4,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x8c, 0x2b, 0x24, 0xc2, 0xc5, 0x9a, 0x54, 0x9a, 0x99,
	0x93, 0x22, 0xc1, 0x04, 0x16, 0x87, 0x70, 0x8c, 0x3c, 0xb8, 0xd8, 0xa1, 0x26, 0x08, 0xd9, 0x22,
	0x98, 0xe2, 0x7a, 0x30, 0x0b, 0x51, 0x8d, 0x97, 0xc2, 0x25, 0xa1, 0xc4, 0x90, 0xc4, 0x06, 0x76,
	0x9b, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xa4, 0x72, 0x95, 0xac, 0x00, 0x00, 0x00,
}
