services:
  homecontrol:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
      - ${HOME}/.philips-hue.json:/home/vscode/.philips-hue.json
    ports:
      - '50051:50051'
    command: sleep infinity
