// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hue.proto

/*
Package hue is a generated protocol buffer package.

It is generated from these files:
	hue.proto

It has these top-level messages:
	EchoMessage
	LightsRequest
	LightsResponse
	Groups
	Group
*/
package hue

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EchoMessage struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *EchoMessage) Reset()                    { *m = EchoMessage{} }
func (m *EchoMessage) String() string            { return proto.CompactTextString(m) }
func (*EchoMessage) ProtoMessage()               {}
func (*EchoMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EchoMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LightsRequest struct {
	Group int32 `protobuf:"varint,1,opt,name=Group" json:"Group,omitempty"`
	// Value between 0 and 1
	BrightnessPercent float32 `protobuf:"fixed32,2,opt,name=BrightnessPercent" json:"BrightnessPercent,omitempty"`
}

func (m *LightsRequest) Reset()                    { *m = LightsRequest{} }
func (m *LightsRequest) String() string            { return proto.CompactTextString(m) }
func (*LightsRequest) ProtoMessage()               {}
func (*LightsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LightsRequest) GetGroup() int32 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *LightsRequest) GetBrightnessPercent() float32 {
	if m != nil {
		return m.BrightnessPercent
	}
	return 0
}

type LightsResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *LightsResponse) Reset()                    { *m = LightsResponse{} }
func (m *LightsResponse) String() string            { return proto.CompactTextString(m) }
func (*LightsResponse) ProtoMessage()               {}
func (*LightsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LightsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Groups struct {
	Groups []*Group `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
}

func (m *Groups) Reset()                    { *m = Groups{} }
func (m *Groups) String() string            { return proto.CompactTextString(m) }
func (*Groups) ProtoMessage()               {}
func (*Groups) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Groups) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type Group struct {
	ID         int32  `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	On         bool   `protobuf:"varint,3,opt,name=On" json:"On,omitempty"`
	Brightness int32  `protobuf:"varint,4,opt,name=Brightness" json:"Brightness,omitempty"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Group) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetOn() bool {
	if m != nil {
		return m.On
	}
	return false
}

func (m *Group) GetBrightness() int32 {
	if m != nil {
		return m.Brightness
	}
	return 0
}

func init() {
	proto.RegisterType((*EchoMessage)(nil), "hue.EchoMessage")
	proto.RegisterType((*LightsRequest)(nil), "hue.LightsRequest")
	proto.RegisterType((*LightsResponse)(nil), "hue.LightsResponse")
	proto.RegisterType((*Groups)(nil), "hue.Groups")
	proto.RegisterType((*Group)(nil), "hue.Group")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Lights service

type LightsClient interface {
	Echo(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoMessage, error)
	GetGroups(ctx context.Context, in *LightsRequest, opts ...grpc.CallOption) (*Groups, error)
	SwitchOn(ctx context.Context, in *LightsRequest, opts ...grpc.CallOption) (*LightsResponse, error)
	SwitchOff(ctx context.Context, in *LightsRequest, opts ...grpc.CallOption) (*LightsResponse, error)
	Blink(ctx context.Context, in *LightsRequest, opts ...grpc.CallOption) (*LightsResponse, error)
}

type lightsClient struct {
	cc *grpc.ClientConn
}

func NewLightsClient(cc *grpc.ClientConn) LightsClient {
	return &lightsClient{cc}
}

func (c *lightsClient) Echo(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoMessage, error) {
	out := new(EchoMessage)
	err := grpc.Invoke(ctx, "/hue.Lights/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightsClient) GetGroups(ctx context.Context, in *LightsRequest, opts ...grpc.CallOption) (*Groups, error) {
	out := new(Groups)
	err := grpc.Invoke(ctx, "/hue.Lights/GetGroups", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightsClient) SwitchOn(ctx context.Context, in *LightsRequest, opts ...grpc.CallOption) (*LightsResponse, error) {
	out := new(LightsResponse)
	err := grpc.Invoke(ctx, "/hue.Lights/SwitchOn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightsClient) SwitchOff(ctx context.Context, in *LightsRequest, opts ...grpc.CallOption) (*LightsResponse, error) {
	out := new(LightsResponse)
	err := grpc.Invoke(ctx, "/hue.Lights/SwitchOff", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightsClient) Blink(ctx context.Context, in *LightsRequest, opts ...grpc.CallOption) (*LightsResponse, error) {
	out := new(LightsResponse)
	err := grpc.Invoke(ctx, "/hue.Lights/Blink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Lights service

type LightsServer interface {
	Echo(context.Context, *EchoMessage) (*EchoMessage, error)
	GetGroups(context.Context, *LightsRequest) (*Groups, error)
	SwitchOn(context.Context, *LightsRequest) (*LightsResponse, error)
	SwitchOff(context.Context, *LightsRequest) (*LightsResponse, error)
	Blink(context.Context, *LightsRequest) (*LightsResponse, error)
}

func RegisterLightsServer(s *grpc.Server, srv LightsServer) {
	s.RegisterService(&_Lights_serviceDesc, srv)
}

func _Lights_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightsServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hue.Lights/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightsServer).Echo(ctx, req.(*EchoMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lights_GetGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightsServer).GetGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hue.Lights/GetGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightsServer).GetGroups(ctx, req.(*LightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lights_SwitchOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightsServer).SwitchOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hue.Lights/SwitchOn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightsServer).SwitchOn(ctx, req.(*LightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lights_SwitchOff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightsServer).SwitchOff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hue.Lights/SwitchOff",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightsServer).SwitchOff(ctx, req.(*LightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lights_Blink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightsServer).Blink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hue.Lights/Blink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightsServer).Blink(ctx, req.(*LightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lights_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hue.Lights",
	HandlerType: (*LightsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Lights_Echo_Handler,
		},
		{
			MethodName: "GetGroups",
			Handler:    _Lights_GetGroups_Handler,
		},
		{
			MethodName: "SwitchOn",
			Handler:    _Lights_SwitchOn_Handler,
		},
		{
			MethodName: "SwitchOff",
			Handler:    _Lights_SwitchOff_Handler,
		},
		{
			MethodName: "Blink",
			Handler:    _Lights_Blink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hue.proto",
}

func init() { proto.RegisterFile("hue.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xa5, 0x2d, 0x54, 0x3a, 0x44, 0x82, 0xa3, 0x87, 0x86, 0x18, 0x25, 0x7b, 0x22, 0x04, 0x7b,
	0xc0, 0xe8, 0x07, 0x34, 0x18, 0x24, 0x51, 0x21, 0xe5, 0xe8, 0x09, 0xeb, 0xd0, 0x36, 0x4a, 0x17,
	0x3b, 0xad, 0x7e, 0x83, 0x7f, 0x6d, 0x76, 0x29, 0x01, 0x82, 0x17, 0x6e, 0xb3, 0x6f, 0xde, 0xdb,
	0x79, 0xf3, 0x32, 0xe0, 0xc4, 0x05, 0x79, 0xab, 0x4c, 0xe6, 0x12, 0xad, 0xb8, 0x20, 0x71, 0x0d,
	0x8d, 0x87, 0x30, 0x96, 0xcf, 0xc4, 0x3c, 0x8f, 0x08, 0x5b, 0x60, 0x2d, 0x39, 0x72, 0x8d, 0x8e,
	0xd1, 0x75, 0x02, 0x55, 0x8a, 0x19, 0x9c, 0x3e, 0x25, 0x51, 0x9c, 0x73, 0x40, 0x5f, 0x05, 0x71,
	0x8e, 0x17, 0x50, 0x1b, 0x65, 0xb2, 0x58, 0x69, 0x52, 0x2d, 0x58, 0x3f, 0xb0, 0x0f, 0x67, 0x7e,
	0xa6, 0x78, 0x29, 0x31, 0x4f, 0x29, 0x0b, 0x29, 0xcd, 0x5d, 0xb3, 0x63, 0x74, 0xcd, 0xe0, 0xb0,
	0x21, 0x7a, 0xd0, 0xdc, 0x7c, 0xca, 0x2b, 0x99, 0x32, 0xa1, 0x0b, 0x27, 0x5c, 0x84, 0x21, 0x31,
	0xeb, 0x7f, 0xeb, 0xc1, 0xe6, 0x29, 0xfa, 0x60, 0xeb, 0x11, 0x8c, 0x02, 0xec, 0x48, 0x57, 0xae,
	0xd1, 0xb1, 0xba, 0x8d, 0x01, 0x78, 0x6a, 0x19, 0xdd, 0x0c, 0xca, 0x8e, 0x78, 0x2d, 0xdd, 0x61,
	0x13, 0xcc, 0xf1, 0xb0, 0xf4, 0x68, 0x8e, 0x87, 0x88, 0x50, 0x7d, 0x99, 0x2f, 0x49, 0x7b, 0x72,
	0x02, 0x5d, 0x2b, 0xce, 0x24, 0x75, 0x2d, 0x3d, 0xcf, 0x9c, 0xa4, 0x78, 0x05, 0xb0, 0xf5, 0xea,
	0x56, 0xb5, 0x76, 0x07, 0x19, 0xfc, 0x9a, 0x60, 0xaf, 0x7d, 0x63, 0x1f, 0xaa, 0x2a, 0x37, 0x6c,
	0x69, 0x0f, 0x3b, 0x11, 0xb6, 0x0f, 0x10, 0x51, 0x41, 0x0f, 0x9c, 0x11, 0xe5, 0xe5, 0x1a, 0xa8,
	0x09, 0x7b, 0xa1, 0xb6, 0x1b, 0xdb, 0x55, 0x58, 0x54, 0xf0, 0x0e, 0xea, 0xb3, 0x9f, 0x24, 0x0f,
	0xe3, 0x49, 0xfa, 0x2f, 0xfd, 0x7c, 0x0f, 0x5b, 0x47, 0x28, 0x2a, 0x78, 0x0f, 0x4e, 0x29, 0x5b,
	0x2c, 0x8e, 0xd1, 0x0d, 0xa0, 0xe6, 0x7f, 0x26, 0xe9, 0xc7, 0x11, 0x1a, 0xbf, 0x07, 0x97, 0xa1,
	0x5c, 0x7a, 0xc9, 0xbb, 0xbc, 0x61, 0xca, 0xbe, 0x93, 0x90, 0xd8, 0xd3, 0x80, 0xcc, 0x95, 0xc0,
	0xaf, 0x3f, 0x16, 0x34, 0x55, 0x77, 0x36, 0x35, 0xde, 0x6c, 0x7d, 0x70, 0xb7, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xc1, 0x21, 0x7d, 0xa9, 0x7d, 0x02, 0x00, 0x00,
}
